In [ ]:
# to import csv file 
import pandas as pd

In [ ]:
dataBase = pd.read_csv('marks.scv')
dataBase.columns

Index(['Name', 'Hours', 'Marks'], dtype='object')

In [ ]:
x = dataBase['Hours']
x

0     5
1    10
2     7
3     6
4     1
Name: Hours, dtype: int64

In [ ]:
y = dataBase['Marks']
y

0     50
1    100
2     70
3     60
4     10
Name: Marks, dtype: int64

In [ ]:
# import LinearRegression function from sklearn module
from sklearn.linear_model  import LinearRegression

In [ ]:
model = LinearRegression() 

In [ ]:
# to convert pandas variable into numpy variable we use =>  .values  
x = x.values

In [ ]:
x.shape # here the dimension is 1D

(5,)

In [ ]:
x = x.reshape(5,1) # to convert into 2D we can use reshape function. We do this because LinearRegression model  

In [ ]:
x.shape

(5, 1)

In [ ]:
model.fit(x, y) # traning the model using fit() function

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.predict([[3]]) # this predict function also required 2D array 
                     # therefore on passing 3 we got 30

array([30.])

In [ ]:
model.coef_ # m = coefficient in the expression ( y = mx )  

array([10.])

In [ ]:
# to save the model we need joblib module
import joblib

In [ ]:
joblib.dump(model ,'marks.pk1')

['marks.pk1']

In [ ]:
# to load the module 
mind = joblib.load('marks.pk1')

In [ ]:
mind.predict([[5]])

array([50.])